version: '3.9'
services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "1200:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongodb-data:/data/db
